{
    "jobs": {
        "build": {
            "runs-on": "ubuntu-22.04",
            "steps": [
                {
                    "uses": "actions/checkout@v3"
                },
                {
                    "run": "yarn install"
                },
                {
                    "run": "yarn elm-test"
                },
                {
                    "run": "yarn elm-review"
                }
            ]
        }
    },
    "on": {
        "push": null
    }
}
